name: bund_investment
description: "Bund | Investment App"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  flutter_native_splash: ^2.3.8
  http: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Light.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/lato/Lato-Regular.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/lato/Lato-Bold.ttf
          weight: 600
          style: normal
  
  uses-material-design: true
