name: bund 
description: "Bund | Investment App"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  flutter_native_splash: ^2.3.8
  http: ^1.1.2
  icons_launcher: ^2.1.6
  equatable: ^2.0.5
  flutter_svg: ^2.0.9
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
    - assets/images/logos/
    - assets/svgs/
    - assets/svgs/nav_icons/
    
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Light.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/lato/Lato-Regular.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/lato/Lato-Bold.ttf
          weight: 600
          style: normal
  
  uses-material-design: true
